export interface AfricanCountry {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
  currency: string;
}

export const AFRICAN_COUNTRIES: AfricanCountry[] = [
  { code: "SN", name: "Sénégal", dialCode: "+221", flag: "🇸🇳", currency: "XOF" },
  { code: "CI", name: "Côte d'Ivoire", dialCode: "+225", flag: "🇨🇮", currency: "XOF" },
  { code: "CM", name: "Cameroun", dialCode: "+237", flag: "🇨🇲", currency: "XAF" },
  { code: "BJ", name: "Bénin", dialCode: "+229", flag: "🇧🇯", currency: "XOF" },
  { code: "CD", name: "RD Congo", dialCode: "+243", flag: "🇨🇩", currency: "CDF" },
  { code: "ML", name: "Mali", dialCode: "+223", flag: "🇲🇱", currency: "XOF" },
  { code: "GN", name: "Guinée", dialCode: "+224", flag: "🇬🇳", currency: "GNF" },
  { code: "TG", name: "Togo", dialCode: "+228", flag: "🇹🇬", currency: "XOF" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226", flag: "🇧🇫", currency: "XOF" },
  { code: "GA", name: "Gabon", dialCode: "+241", flag: "🇬🇦", currency: "XAF" },
  { code: "CG", name: "Congo-Brazzaville", dialCode: "+242", flag: "🇨🇬", currency: "XAF" },
  { code: "NE", name: "Niger", dialCode: "+227", flag: "🇳🇪", currency: "XOF" },
  { code: "TD", name: "Tchad", dialCode: "+235", flag: "🇹🇩", currency: "XAF" },
  { code: "CF", name: "Centrafrique", dialCode: "+236", flag: "🇨🇫", currency: "XAF" },
  { code: "MG", name: "Madagascar", dialCode: "+261", flag: "🇲🇬", currency: "MGA" },
  { code: "MA", name: "Maroc", dialCode: "+212", flag: "🇲🇦", currency: "MAD" },
  { code: "DZ", name: "Algérie", dialCode: "+213", flag: "🇩🇿", currency: "DZD" },
  { code: "TN", name: "Tunisie", dialCode: "+216", flag: "🇹🇳", currency: "TND" },
  { code: "MR", name: "Mauritanie", dialCode: "+222", flag: "🇲🇷", currency: "MRU" },
  { code: "RW", name: "Rwanda", dialCode: "+250", flag: "🇷🇼", currency: "RWF" },
  { code: "BI", name: "Burundi", dialCode: "+257", flag: "🇧🇮", currency: "BIF" },
  { code: "DJ", name: "Djibouti", dialCode: "+253", flag: "🇩🇯", currency: "DJF" },
  { code: "KM", name: "Comores", dialCode: "+269", flag: "🇰🇲", currency: "KMF" },
  { code: "MU", name: "Île Maurice", dialCode: "+230", flag: "🇲🇺", currency: "MUR" },
  { code: "SC", name: "Seychelles", dialCode: "+248", flag: "🇸🇨", currency: "SCR" },
  { code: "GQ", name: "Guinée Équatoriale", dialCode: "+240", flag: "🇬🇶", currency: "XAF" },
  { code: "GW", name: "Guinée-Bissau", dialCode: "+245", flag: "🇬🇼", currency: "XOF" },
  { code: "CV", name: "Cap-Vert", dialCode: "+238", flag: "🇨🇻", currency: "CVE" },
  { code: "ST", name: "Sao Tomé-et-Principe", dialCode: "+239", flag: "🇸🇹", currency: "STN" },
  { code: "AO", name: "Angola", dialCode: "+244", flag: "🇦🇴", currency: "AOA" },
  { code: "MZ", name: "Mozambique", dialCode: "+258", flag: "🇲🇿", currency: "MZN" },
  { code: "GH", name: "Ghana", dialCode: "+233", flag: "🇬🇭", currency: "GHS" },
  { code: "NG", name: "Nigéria", dialCode: "+234", flag: "🇳🇬", currency: "NGN" },
  { code: "KE", name: "Kenya", dialCode: "+254", flag: "🇰🇪", currency: "KES" },
  { code: "TZ", name: "Tanzanie", dialCode: "+255", flag: "🇹🇿", currency: "TZS" },
  { code: "UG", name: "Ouganda", dialCode: "+256", flag: "🇺🇬", currency: "UGX" },
  { code: "ET", name: "Éthiopie", dialCode: "+251", flag: "🇪🇹", currency: "ETB" },
  { code: "ZA", name: "Afrique du Sud", dialCode: "+27", flag: "🇿🇦", currency: "ZAR" },
  { code: "EG", name: "Égypte", dialCode: "+20", flag: "🇪🇬", currency: "EGP" },
  { code: "ZM", name: "Zambie", dialCode: "+260", flag: "🇿🇲", currency: "ZMW" },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263", flag: "🇿🇼", currency: "ZWL" },
  { code: "BW", name: "Botswana", dialCode: "+267", flag: "🇧🇼", currency: "BWP" },
  { code: "NA", name: "Namibie", dialCode: "+264", flag: "🇳🇦", currency: "NAD" },
  { code: "LR", name: "Libéria", dialCode: "+231", flag: "🇱🇷", currency: "LRD" },
  { code: "SL", name: "Sierra Leone", dialCode: "+232", flag: "🇸🇱", currency: "SLE" },
  { code: "GM", name: "Gambie", dialCode: "+220", flag: "🇬🇲", currency: "GMD" },
  { code: "MW", name: "Malawi", dialCode: "+265", flag: "🇲🇼", currency: "MWK" },
  { code: "SO", name: "Somalie", dialCode: "+252", flag: "🇸🇴", currency: "SOS" },
  { code: "SD", name: "Soudan", dialCode: "+249", flag: "🇸🇩", currency: "SDG" },
  { code: "SS", name: "Soudan du Sud", dialCode: "+211", flag: "🇸🇸", currency: "SSP" },
  { code: "LY", name: "Libye", dialCode: "+218", flag: "🇱🇾", currency: "LYD" },
  { code: "SZ", name: "Eswatini", dialCode: "+268", flag: "🇸🇿", currency: "SZL" },
  { code: "LS", name: "Lesotho", dialCode: "+266", flag: "🇱🇸", currency: "LSL" },
  { code: "ER", name: "Érythrée", dialCode: "+291", flag: "🇪🇷", currency: "ERN" },
  // Diaspora panafricaine majeure
  { code: "FR", name: "France (Diaspora)", dialCode: "+33", flag: "🇫🇷", currency: "EUR" },
  { code: "BE", name: "Belgique (Diaspora)", dialCode: "+32", flag: "🇧🇪", currency: "EUR" },
  { code: "CA", name: "Canada (Diaspora)", dialCode: "+1", flag: "🇨🇦", currency: "CAD" },
  { code: "US", name: "États-Unis (Diaspora)", dialCode: "+1", flag: "🇺🇸", currency: "USD" },
  { code: "GB", name: "Royaume-Uni (Diaspora)", dialCode: "+44", flag: "🇬🇧", currency: "GBP" },
];
