export enum AccountStatus {
  UNVERIFIED = "UNVERIFIED",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  SUSPENDED = "SUSPENDED",
  BANNED = "BANNED",
  DELETED = "DELETED",
}

export enum RoleType {
  USER = "USER",
  CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT",
  MODERATOR = "MODERATOR",
  LEAD_MODERATOR = "LEAD_MODERATOR",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
}

export enum FamilyStatus {
  SINGLE_NO_CHILDREN = "SINGLE_NO_CHILDREN",
  SINGLE_WITH_CHILDREN = "SINGLE_WITH_CHILDREN",
  DIVORCED_NO_CHILDREN = "DIVORCED_NO_CHILDREN",
  DIVORCED_WITH_CHILDREN = "DIVORCED_WITH_CHILDREN",
  WIDOWED = "WIDOWED",
}

export enum PhotoModerationStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum VerificationStatus {
  NOT_STARTED = "NOT_STARTED",
  PENDING = "PENDING",
  UNDER_REVIEW = "UNDER_REVIEW",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
  SUPPLEMENTARY_INFO_REQUIRED = "SUPPLEMENTARY_INFO_REQUIRED",
  SUSPENDED = "SUSPENDED",
}

export enum DocumentType {
  NATIONAL_ID = "NATIONAL_ID",
  PASSPORT = "PASSPORT",
  VOTER_CARD = "VOTER_CARD",
  RESIDENCE_PERMIT = "RESIDENCE_PERMIT",
  SELFIE = "SELFIE",
}

export enum MessageStatus {
  SENT = "SENT",
  DELIVERED = "DELIVERED",
  READ = "READ",
}

export enum ReportCategory {
  INAPPROPRIATE_PROFILE = "INAPPROPRIATE_PROFILE",
  OBSCENE_PHOTO = "OBSCENE_PHOTO",
  HARASSMENT_MESSAGE = "HARASSMENT_MESSAGE",
  FINANCIAL_SCAM_SOLICITATION = "FINANCIAL_SCAM_SOLICITATION",
  IDENTITY_THEFT = "IDENTITY_THEFT",
  UNDERAGE_SUSPICION = "UNDERAGE_SUSPICION",
  SUSPICIOUS_BEHAVIOR = "SUSPICIOUS_BEHAVIOR",
}

export enum ReportPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum ModActionType {
  WARNING_SENT = "WARNING_SENT",
  INFO_REQUESTED = "INFO_REQUESTED",
  PHOTO_HIDDEN = "PHOTO_HIDDEN",
  TEMP_RESTRICTION = "TEMP_RESTRICTION",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
  ACCOUNT_BANNED = "ACCOUNT_BANNED",
  RE_VERIFICATION_REQUIRED = "RE_VERIFICATION_REQUIRED",
  CASE_DISMISSED = "CASE_DISMISSED",
  ESCALATED_TO_LEAD = "ESCALATED_TO_LEAD",
}

export enum PaymentProviderType {
  MOCK_TEST = "MOCK_TEST",
  WAVE = "WAVE",
  ORANGE_MONEY = "ORANGE_MONEY",
  MTN_MOMO = "MTN_MOMO",
  MOOV_MONEY = "MOOV_MONEY",
  STRIPE = "STRIPE",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  SUCCESSFUL = "SUCCESSFUL",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum ModerationStatus {
  OPEN = "OPEN",
  ASSIGNED = "ASSIGNED",
  UNDER_REVIEW = "UNDER_REVIEW",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}

export enum PlanInterval {
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  YEARLY = "YEARLY",
}

export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  PAST_DUE = "PAST_DUE",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
}

export enum NotificationChannel {
  IN_APP = "IN_APP",
  PUSH = "PUSH",
  SMS = "SMS",
  EMAIL = "EMAIL",
}

export enum NotificationType {
  OTP_CODE = "OTP_CODE",
  KYC_APPROVED = "KYC_APPROVED",
  KYC_REJECTED = "KYC_REJECTED",
  NEW_MATCH = "NEW_MATCH",
  NEW_MESSAGE = "NEW_MESSAGE",
  PHOTO_MODERATED = "PHOTO_MODERATED",
  REPORT_UPDATE = "REPORT_UPDATE",
  SUBSCRIPTION_CONFIRMED = "SUBSCRIPTION_CONFIRMED",
  SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED",
}

export enum RequestProcessStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}
